"""Correction bookings

Revision ID: 8a2922671d2e
Revises: 0e02d8e2e04e
Create Date: 2026-06-20 11:04:17.419506

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8a2922671d2e'
down_revision: Union[str, Sequence[str], None] = '0e02d8e2e04e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("""
        UPDATE bookings 
        SET total_cost = EXTRACT(EPOCH FROM (date_to - date_from)) * price
    """)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
