"""try_fix_columns_in_Bookings

Revision ID: 332ff00a581b
Revises: 6dc23ba23521
Create Date: 2026-07-07 16:53:28.820329

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '332ff00a581b'
down_revision: Union[str, Sequence[str], None] = '6dc23ba23521'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    pass


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
