"""FixBookings

Revision ID: 6dc23ba23521
Revises: 46813304c141
Create Date: 2026-07-07 16:43:17.243085

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6dc23ba23521'
down_revision: Union[str, Sequence[str], None] = '46813304c141'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    pass


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
